language: node_js
node_js:
  - stable
  - iojs
  - '0.10'
  - '0.12'
os:
  - linux
  - windows
before_script:
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g coveralls
after_script:
  - npm run coverage
  - npm run coveralls
services:
  - redis-server